/**
 * Angular.Schule Book API
 * Simple HTTP backend for serving books
 *
 * The version of the OpenAPI document: 0.0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * An object with a rating value (1...5)
 */
export interface Rating { 
    /**
     * Rating value for a book from one star (bad) to five stars (great)
     */
    rating: number;
}

