/**
 * Angular.Schule Book API
 * Simple HTTP backend for serving books
 *
 * The version of the OpenAPI document: 0.0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * Link to an image, which is used as a thumbnail
 */
export interface Thumbnail { 
    /**
     * Image to display
     */
    url: string;
    /**
     * Caption of the image
     */
    title: string;
}

